require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

target 'PolarisMaps' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']
  use_modular_headers!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
# @generated begin @maplibre/maplibre-react-native:post-install - expo prebuild (DO NOT MODIFY) sync-6e76c80af0d70c0003d06822dd59b7c729fca472
    $MLRN.post_install(installer)
# @generated end @maplibre/maplibre-react-native:post-install
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end

    # Disable Clang module dependency scanning. CocoaPods with use_modular_headers!
    # generates -fmodule-map-file flags pointing to DerivedData, which doesn't exist
    # on a clean build (e.g. after restarting Xcode/computer). The scanner then fails
    # to find EXConstants.modulemap and cascades into "could not build module" errors.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['ENABLE_MODULE_DEPENDENCY_SCANNING'] = 'NO'
      end
    end
    installer.generated_projects.each do |project|
      project.build_configurations.each do |config|
        config.build_settings['ENABLE_MODULE_DEPENDENCY_SCANNING'] = 'NO'
      end
    end
    user_project_path = File.join(__dir__, 'PolarisMaps.xcodeproj')
    if File.exist?(user_project_path)
      user_project = Xcodeproj::Project.open(user_project_path)
      user_project.build_configurations.each do |config|
        config.build_settings['ENABLE_MODULE_DEPENDENCY_SCANNING'] = 'NO'
      end
      user_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_MODULE_DEPENDENCY_SCANNING'] = 'NO'
        end
      end
      user_project.save
    end

    # Fix fmt 11.x consteval issue with iOS 26 SDK / Xcode 26.
    # Patches fmt/base.h after pod install downloads fresh sources.
    fmt_base_h = File.join(__dir__, 'Pods', 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base_h)
      content = File.read(fmt_base_h)
      unless content.include?('FMT_CONSTEVAL_PATCHED')
        lines = content.lines
        new_lines = []
        i = 0
        while i < lines.length
          line = lines[i]
          if line.include?('Detect consteval, C++20 constexpr extensions')
            new_lines << "// FMT_CONSTEVAL_PATCHED: Force consteval off for iOS 26 SDK / Xcode 26 compatibility.\n"
            new_lines << "#define FMT_USE_CONSTEVAL 0\n"
            new_lines << "#define FMT_CONSTEVAL\n"
            new_lines << "#define FMT_CONSTEXPR20\n"
            found_first_endif = false
            i += 1
            while i < lines.length
              if lines[i].strip == '#if FMT_USE_CONSTEVAL' && found_first_endif
                i += 1
                while i < lines.length
                  break if lines[i].strip == '#endif'
                  i += 1
                end
                break
              end
              if lines[i].strip == '#endif' && !found_first_endif
                found_first_endif = true
              end
              i += 1
            end
          else
            new_lines << line
          end
          i += 1
        end
        FileUtils.chmod(0644, fmt_base_h)
        File.write(fmt_base_h, new_lines.join)
      end
    end

  end
end
